'use strict';
const VIDEO=/\.(?:m3u8|mp4|webm|m4v|mov|mp3|m4a|aac)(?:[?#]|$)/i;
async function apiBase(){const {port}=await chrome.storage.local.get({port:3021});const n=Number(port);if(!Number.isInteger(n)||n<1024||n>65535)throw Error('Choose a port between 1024 and 65535.');return 'http://127.0.0.1:'+n;}
const sessions=new Map(),requestHeaders=new Map(),writes=new Map();
async function health(){try{const r=await fetch((await apiBase())+'/wdm-health',{signal:AbortSignal.timeout(2500)}),j=await r.json();return r.ok&&j.app==='WDM 2';}catch{return false;}}
async function request(route,payload){const r=await fetch((await apiBase())+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(90000)}),j=await r.json();if(!r.ok||!(route==='/'?j.accepted===true&&j.captured===true:j.ok===true))throw Error(j.error||'WDM could not accept this download.');return j;}
async function itemsFor(id){if(sessions.has(id))return sessions.get(id);const s=await chrome.storage.session.get('media:'+id),list=s['media:'+id]||[];sessions.set(id,list);return list;}
function serialize(id,fn){const next=(writes.get(id)||Promise.resolve()).catch(()=>{}).then(fn);writes.set(id,next);next.finally(()=>{if(writes.get(id)===next)writes.delete(id);}).catch(()=>{});return next;}
function remember(id,item){if(id<0)return;serialize(id,async()=>{const list=await itemsFor(id),i=list.findIndex(x=>x.url===item.url);if(i>=0)list[i]={...list[i],...item};else list.push(item);if(list.length>100)list.splice(0,list.length-100);sessions.set(id,list);await chrome.storage.session.set({['media:'+id]:list});await chrome.action.setBadgeText({tabId:id,text:String(list.length)}).catch(()=>{});await chrome.action.setBadgeBackgroundColor({tabId:id,color:'#10a37f'}).catch(()=>{});});}
async function send(url,filename='',source='browser',tabUrl='',tabId){if(!/^https?:\/\//i.test(url||''))throw Error('Blob URLs need an underlying media request. Play the video and choose a detected MP4 or HLS link.');const known=(await itemsFor(tabId??-1)).find(x=>x.url===url),headers={'user-agent':navigator.userAgent,'accept':'*/*','accept-language':navigator.language||'en-US',...(known?.headers||{})};try{const cookies=await chrome.cookies.getAll({url});if(cookies.length)headers.cookie=cookies.map(c=>`${c.name}=${c.value}`).join('; ');}catch{}if(tabUrl)headers.referer=tabUrl;const hls=known?.type==='HLS'||/\.m3u8(?:[?#]|$)/i.test(url);return request('/',hls?{extensionVersion:'2.0.1',type:'m3u8',m3u8Url:url,headers,refererHeader:tabUrl,suggestedName:filename,tabId:tabId??-1}:{extensionVersion:'2.0.1',type:'single',data:{url,referer:tabUrl,cookie:headers.cookie,headers}});}
function notify(message){chrome.notifications.create({type:'basic',iconUrl:'icons/128.png',title:'WDM',message:String(message).slice(0,300)}).catch(()=>{});}
chrome.webRequest.onBeforeSendHeaders.addListener(d=>{if(d.tabId<0)return;const h={};for(const x of d.requestHeaders||[])if(['authorization','referer','user-agent'].includes(x.name.toLowerCase()))h[x.name.toLowerCase()]=x.value;requestHeaders.set(d.requestId,h);if(requestHeaders.size>400)requestHeaders.delete(requestHeaders.keys().next().value);},{urls:['http://*/*','https://*/*']},['requestHeaders','extraHeaders']);
chrome.webRequest.onResponseStarted.addListener(d=>{const h=requestHeaders.get(d.requestId)||{};requestHeaders.delete(d.requestId);if(d.tabId<0)return;const mime=(d.responseHeaders||[]).find(h=>h.name.toLowerCase()==='content-type')?.value||'';if(d.statusCode<200||d.statusCode>=300||!VIDEO.test(d.url)&&!/(video\/(?:mp4|webm|quicktime)|audio\/(?:mpeg|mp4)|mpegurl)/i.test(mime)||/\.(ts|m4s)(?:[?#]|$)/i.test(d.url))return;const hls=/mpegurl/i.test(mime)||/\.m3u8(?:[?#]|$)/i.test(d.url);remember(d.tabId,{url:d.url,type:hls?'HLS':'Video',label:hls?'HLS recording':new URL(d.url).pathname.split('/').pop()||'Video',headers:h,at:Date.now()});},{urls:['http://*/*','https://*/*']},['responseHeaders']);
chrome.webRequest.onErrorOccurred.addListener(d=>requestHeaders.delete(d.requestId),{urls:['http://*/*','https://*/*']});
chrome.tabs.onUpdated.addListener((id,info)=>{if(info.status==='loading')serialize(id,async()=>{sessions.delete(id);await chrome.storage.session.remove('media:'+id);await chrome.action.setBadgeText({tabId:id,text:''}).catch(()=>{});});});
chrome.tabs.onRemoved.addListener(id=>serialize(id,async()=>{sessions.delete(id);await chrome.storage.session.remove('media:'+id);}));
chrome.runtime.onInstalled.addListener(async()=>{const s=await chrome.storage.local.get({capture:true});await chrome.storage.local.set({capture:s.capture});await chrome.contextMenus.removeAll();chrome.contextMenus.create({id:'wdm-link',title:'Download with WDM',contexts:['link']});chrome.contextMenus.create({id:'wdm-media',title:'Download media with WDM',contexts:['video','audio','image']});});
chrome.contextMenus.onClicked.addListener(async(info,tab)=>{try{if(!await health())throw Error('Open WDM from your desktop shortcut first.');await send(info.linkUrl||info.srcUrl,'','context-menu',tab?.url||'',tab?.id);}catch(e){notify(e.message);}});
chrome.downloads.onCreated.addListener(async item=>{const s=await chrome.storage.local.get({capture:true});if(!s.capture||!/^https?:\/\//i.test(item.finalUrl||item.url||'')||!await health())return;let paused=false;try{try{await chrome.downloads.pause(item.id);paused=true;}catch{}await send(item.finalUrl||item.url,item.filename?.split(/[\\/]/).pop()||'','auto-capture',item.referrer||'');await chrome.downloads.cancel(item.id);await chrome.downloads.erase({id:item.id});}catch(e){if(paused)await chrome.downloads.resume(item.id).catch(()=>{});notify('Browser download kept: '+e.message);}});
chrome.runtime.onMessage.addListener((msg,sender,reply)=>{(async()=>{const id=sender.tab?.id??msg.tabId;if(msg.type==='health')return {ok:await health()};if(msg.type==='get-media'){await writes.get(id);return {ok:true,items:(await itemsFor(id)).map(({headers,...x})=>x)};}if(msg.type==='send')return {ok:true,result:await send(msg.url,msg.filename||'',msg.source||'popup',sender.tab?.url||msg.tabUrl||'',id)};if(msg.type==='open'){if(!await health())throw Error('Open WDM from the desktop shortcut first.');await request('/wdm-open',{});return {ok:true};}return {ok:false,error:'Unknown action.'};})().then(reply).catch(e=>reply({ok:false,error:e.message}));return true;});
