'use strict';
(()=>{
 const FILE=/\.(zip|rar|7z|exe|msi|pdf|docx?|xlsx?|pptx?|iso|mp4|webm|mkv|m3u8|mp3|m4a|wav|flac|jpe?g|png|webp|gif|epub)(?:[?#]|$)/i,MEDIA=/\.(m3u8|mp4|webm|m4v|mov|mp3|m4a)(?:[?#]|$)/i;
 let host,shadow,closed=false,blobDetected=false;
 function collect(){const items=new Map();blobDetected=false;const add=(url,label,type)=>{try{const u=new URL(url,location.href);if(u.protocol==='blob:'){blobDetected=true;return;}if(!['http:','https:'].includes(u.protocol))return;items.set(u.href,{url:u.href,label:(label||u.pathname.split('/').pop()||u.hostname).slice(0,160),type:/\.m3u8(?:[?#]|$)/i.test(u.href)?'HLS':type});}catch{}};document.querySelectorAll('video,audio,source').forEach(el=>{if(el.currentSrc||el.src)add(el.currentSrc||el.src,el.title||'Page media','Video');});document.querySelectorAll('a[href]').forEach(a=>{if(a.hasAttribute('download')||FILE.test(a.href))add(a.href,a.textContent.trim(),'File');});try{performance.getEntriesByType('resource').forEach(e=>{if(MEDIA.test(e.name))add(e.name,'Detected media','Video');});}catch{}return [...items.values()].slice(0,300);}
 async function all(){const dom=collect();let network=[];try{network=(await chrome.runtime.sendMessage({type:'get-media'}))?.items||[];}catch{}return [...new Map([...dom,...network].map(x=>[x.url,x])).values()];}
 chrome.runtime.onMessage.addListener((m,_s,r)=>{if(m.type==='collect'){all().then(items=>r({items,blobDetected}));return true;}});
 async function panel(){const list=shadow.querySelector('.list');list.hidden=!list.hidden;if(list.hidden)return;list.replaceChildren();const media=(await all()).filter(x=>x.type!=='File');if(!media.length){const p=document.createElement('p');p.textContent=blobDetected?'Blob player found. Play the video to detect its MP4 or HLS request. DRM streams cannot be downloaded.':'Play the video, then reopen this list.';list.append(p);return;}for(const item of media.slice(0,30)){const row=document.createElement('div'),title=document.createElement('span'),b=document.createElement('button');row.className='item';title.textContent=item.type+' · '+item.label;title.title=item.url;b.textContent='Download';b.onclick=async()=>{b.disabled=true;b.textContent='Sending…';try{const r=await chrome.runtime.sendMessage({type:'send',url:item.url,source:'floating-video'});if(!r?.ok)throw Error(r?.error||'Could not contact WDM.');b.textContent='Queued';}catch(e){b.textContent='Retry';b.disabled=false;const p=document.createElement('p');p.textContent=e.message;row.append(p);}};row.append(title,b);list.append(row);}}
 function mount(){if(closed||host||!document.querySelector('video,audio'))return;host=document.createElement('div');host.id='wdm-video-control';host.style.cssText='all:initial;position:fixed;right:18px;bottom:24px;z-index:2147483646;';shadow=host.attachShadow({mode:'closed'});const style=document.createElement('style');style.textContent=':host{font-family:Segoe UI,Arial,sans-serif}*{box-sizing:border-box}button{font:600 12px Segoe UI;color:#fff;border:0;border-radius:5px;background:#176d58;padding:9px 12px;cursor:pointer}button:disabled{opacity:.6}.bar{display:flex;gap:2px;justify-content:flex-end}.list{background:#fff;color:#222;box-shadow:0 5px 22px #0004;border:1px solid #ddd;border-radius:7px;margin-bottom:6px;width:350px;max-width:80vw;max-height:300px;overflow:auto;padding:8px}.list[hidden]{display:none}.item{display:flex;align-items:center;gap:8px;flex-wrap:wrap;border-bottom:1px solid #eee;padding:8px 2px}.item span{flex:1;min-width:120px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}p{font-size:12px;line-height:1.5;margin:5px}.item button{padding:6px;font-size:11px}';const list=document.createElement('div');list.className='list';list.hidden=true;const bar=document.createElement('div');bar.className='bar';const button=document.createElement('button');button.textContent='↓ Download video';button.onclick=panel;const close=document.createElement('button');close.textContent='×';close.title='Hide on this page';close.onclick=()=>{closed=true;host.remove();};bar.append(button,close);shadow.append(style,list,bar);document.documentElement.append(host);}
 mount();let timer;new MutationObserver(()=>{if(host||closed)return;clearTimeout(timer);timer=setTimeout(mount,600);}).observe(document.documentElement,{childList:true,subtree:true});
})();
