'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {setTimeout:wait}=require('node:timers/promises');
const {JSDOM}=require('jsdom');
const base=path.resolve(process.argv[2]||'.');
const results=[];
async function test(name,fn){try{const detail=await fn();results.push({name,status:'PASS',detail:detail||''});}catch(e){results.push({name,status:'FAIL',detail:e.message});}}
function background(opts={}){
 const hooks={},sent=[],actions=[],session={},event=n=>({addListener:fn=>hooks[n]=fn});
 const chrome={runtime:{onMessage:event('message'),onInstalled:event('install')},storage:{session:{get:async k=>({[k]:session[k]}),set:async o=>Object.assign(session,o),remove:async k=>delete session[k]},local:{get:async d=>({...d,capture:opts.capture!==false,port:opts.port||3021}),set:async()=>{}}},action:{setBadgeText:async()=>{},setBadgeBackgroundColor:async()=>{}},cookies:{getAll:async()=>[{name:'sid',value:'test-session'}]},notifications:{create:async()=>{}},contextMenus:{removeAll:async()=>{},create:()=>{},onClicked:event('context')},webRequest:{onBeforeSendHeaders:event('headers'),onResponseStarted:event('response'),onErrorOccurred:event('error')},tabs:{onUpdated:event('update'),onRemoved:event('remove')},downloads:{onCreated:event('download'),pause:async()=>actions.push('pause'),cancel:async()=>actions.push('cancel'),erase:async()=>actions.push('erase'),resume:async()=>actions.push('resume')}};
 const fetch=async(url,init)=>{sent.push({url,init});if(opts.offline)throw Error('offline');return{ok:true,json:async()=>url.endsWith('/wdm-health')?{app:opts.identity||'WDM 2'}:url.endsWith('/wdm-open')?{ok:true}:{captured:opts.accept!==false,accepted:opts.durable!==false&&opts.accept!==false}}};
 vm.runInNewContext(fs.readFileSync(path.join(base,'extension/background.js'),'utf8'),{chrome,navigator:{userAgent:'audit-fixture',language:'en'},URL,AbortSignal,Map,Promise,fetch,console});
 const message=(msg)=>new Promise(resolve=>hooks.message(msg,{tab:{id:3,url:'https://example.test/page'}},resolve));
 const detect=(url,mime='video/mp4',status=200)=>{hooks.headers({tabId:3,requestId:url,requestHeaders:[{name:'Authorization',value:'Bearer fixture'}]});hooks.response({tabId:3,requestId:url,url,statusCode:status,responseHeaders:[{name:'Content-Type',value:mime}]});};
 return{hooks,sent,actions,session,message,detect};
}
async function popup(){
 const dom=new JSDOM(fs.readFileSync(path.join(base,'extension/popup.html'),'utf8'),{url:'https://wdm-extension.test/popup.html',runScripts:'outside-only'}),w=dom.window;
 w.chrome={storage:{local:{get:async()=>({capture:true}),set:async()=>{}}},tabs:{query:async()=>[{id:3,url:'https://example.test/page'}],sendMessage:async()=>({items:[{url:'https://example.test/file.zip',type:'File',label:'Test archive'}]})},runtime:{sendMessage:async m=>m.type==='get-media'?{ok:true,items:[]}:{ok:true}}};
 w.eval(fs.readFileSync(path.join(base,'extension/popup.js'),'utf8'));await wait(15);return dom;
}
(async()=>{
 await test('Health accepts WDM 2',async()=>assert.equal((await background().message({type:'health'})).ok,true));
 await test('Health rejects a different application',async()=>assert.equal((await background({identity:'Brisk'}).message({type:'health'})).ok,false));
 await test('Offline desktop leaves browser download untouched',async()=>{const b=background({offline:true});await b.hooks.download({id:1,url:'https://example.test/a.zip'});assert.equal(b.actions.length,0);});
 await test('Capture disabled leaves browser download untouched',async()=>{const b=background({capture:false});await b.hooks.download({id:1,url:'https://example.test/a.zip'});assert.equal(b.actions.length,0);});
 await test('Desktop rejection resumes the browser download',async()=>{const b=background({accept:false});await b.hooks.download({id:1,url:'https://example.test/a.zip'});assert.deepEqual(b.actions,['pause','resume']);});
 await test('Positive acknowledgement cancels and erases browser download',async()=>{const b=background();await b.hooks.download({id:1,url:'https://example.test/a.zip'});assert.deepEqual(b.actions,['pause','cancel','erase']);return 'Confirms extension behavior only; desktop must acknowledge only after durable acceptance.';});
 await test('Legacy captured-only acknowledgement preserves browser download',async()=>{const b=background({durable:false});await b.hooks.download({id:1,url:'https://example.test/a.zip'});assert.deepEqual(b.actions,['pause','resume']);});
 await test('Custom port applies to health and download endpoints',async()=>{const b=background({port:4011});await b.message({type:'health'});await b.message({type:'send',url:'https://example.test/a.zip'});assert(b.sent.every(x=>x.url.startsWith('http://127.0.0.1:4011/')));});
 await test('Direct-file handoff includes cookies, Authorization and Referer',async()=>{const b=background();b.detect('https://example.test/a.mp4');await b.message({type:'get-media'});await b.message({type:'send',url:'https://example.test/a.mp4'});const p=JSON.parse(b.sent.at(-1).init.body);assert.equal(p.data.headers.authorization,'Bearer fixture');assert.equal(p.data.cookie,'sid=test-session');assert.equal(p.data.referer,'https://example.test/page');});
 await test('HLS handoff preserves Authorization',async()=>{const b=background();b.detect('https://example.test/list','application/vnd.apple.mpegurl');await b.message({type:'get-media'});await b.message({type:'send',url:'https://example.test/list'});const p=JSON.parse(b.sent.at(-1).init.body);assert.equal(p.headers?.authorization,'Bearer fixture');});
 await test('HLS handoff preserves cookies',async()=>{const b=background();await b.message({type:'send',url:'https://example.test/list.m3u8'});const p=JSON.parse(b.sent.at(-1).init.body);assert.equal(p.headers?.cookie||p.cookie,'sid=test-session');});
 await test('Extensionless HLS detected by MIME type; secrets hidden from listing',async()=>{const b=background();b.detect('https://example.test/list','application/vnd.apple.mpegurl');const r=await b.message({type:'get-media'});assert.equal(r.items[0].type,'HLS');assert.equal(r.items[0].headers,undefined);});
 await test('Media list deduplicates repeated responses',async()=>{const b=background();b.detect('https://example.test/a.mp4');b.detect('https://example.test/a.mp4');assert.equal((await b.message({type:'get-media'})).items.length,1);});
 await test('Media discovery ignores errors and TS fragments',async()=>{const b=background();b.detect('https://example.test/a.mp4','video/mp4',404);b.detect('https://example.test/a.ts','video/mp4');assert.equal((await b.message({type:'get-media'})).items.length,0);});
 await test('Media list is limited to 100 entries per tab',async()=>{const b=background();for(let i=0;i<110;i++)b.detect('https://example.test/'+i+'.mp4');assert.equal((await b.message({type:'get-media'})).items.length,100);});
 await test('Navigation clears stale media',async()=>{const b=background();b.detect('https://example.test/a.mp4');await b.message({type:'get-media'});b.hooks.update(3,{status:'loading'});assert.equal((await b.message({type:'get-media'})).items.length,0);});
 await test('Blob URLs return actionable guidance',async()=>{const r=await background().message({type:'send',url:'blob:https://example.test/a'});assert.equal(r.ok,false);assert.match(r.error,/underlying media request/);});
 await test('Explicit Open WDM message uses its endpoint',async()=>{const b=background();assert.equal((await b.message({type:'open'})).ok,true);assert.equal(b.sent.at(-1).url,'http://127.0.0.1:3021/wdm-open');});
 await test('Popup row selection boxes are hidden initially',async()=>{const d=await popup();try{assert.equal(d.window.getComputedStyle(d.window.document.querySelector('[data-select]')).display,'none');}finally{d.window.close();}});
 await test('Popup batch selection controls are hidden initially',async()=>{const d=await popup();try{assert.equal(d.window.getComputedStyle(d.window.document.querySelector('#selectionControls')).display,'none');}finally{d.window.close();}});
 await test('Popup selection button changes state and clears selection',async()=>{const d=await popup(),w=d.window;try{w.document.querySelector('#selection').click();assert(w.document.body.classList.contains('selecting'));const c=w.document.querySelector('[data-select]');c.checked=true;w.document.querySelector('#selection').click();assert.equal(c.checked,false);assert.equal(w.document.querySelector('#selection').getAttribute('aria-pressed'),'false');}finally{w.close();}});
 await test('Page scan finds direct media, downloadable links and blob player',async()=>{const d=new JSDOM('<video src="blob:https://example.test/abc"></video><source src="/movie.mp4"><a href="/a.zip">Archive</a><a href="/next-page">Page</a>',{url:'https://example.test/page',runScripts:'outside-only'}),w=d.window;let listener,shadow,sent;
 try{const attach=w.Element.prototype.attachShadow;w.Element.prototype.attachShadow=function(o){shadow=attach.call(this,o);return shadow;};w.chrome={runtime:{onMessage:{addListener:fn=>listener=fn},sendMessage:async m=>{if(m.type==='send'){sent=m;return{ok:true};}return{items:[{url:'https://example.test/list.m3u8',type:'HLS',label:'Video'}]};}}};w.eval(fs.readFileSync(path.join(base,'extension/content.js'),'utf8'));const r=await new Promise(resolve=>listener({type:'collect'},{},resolve));assert(r.blobDetected);assert.equal(r.items.length,3);assert(w.document.querySelector('#wdm-video-control'));shadow.querySelector('.bar button').click();await wait(5);shadow.querySelector('.item button').click();await wait(5);assert(sent.url.startsWith('https:'));}finally{w.close();}});
 await test('Finishing selection hides rows and batch controls again',async()=>{const d=await popup(),w=d.window;try{w.document.querySelector('#selection').click();assert.notEqual(w.getComputedStyle(w.document.querySelector('[data-select]')).display,'none');w.document.querySelector('#selection').click();assert.equal(w.getComputedStyle(w.document.querySelector('[data-select]')).display,'none');assert.equal(w.getComputedStyle(w.document.querySelector('#selectionControls')).display,'none');}finally{w.close();}});
 console.log(results.map(x=>x.status+' '+x.name+(x.status==='FAIL'?' — '+x.detail:'')).join('\n'));
 const summary={method:'Actual extension JavaScript executed with Chrome API fixtures and JSDOM 26.1.0; no live browser or Flutter desktop',passed:results.filter(x=>x.status==='PASS').length,failed:results.filter(x=>x.status==='FAIL').length,results};
 fs.writeFileSync('extension-results.json',JSON.stringify(summary,null,2));console.log(JSON.stringify({passed:summary.passed,failed:summary.failed}));if(summary.failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=2;});
