import 'package:wdm/theme/application_theme.dart';
import 'package:flutter/material.dart';

ApplicationTheme celestialDark = const ApplicationTheme(
  themeId: "Celestial Dark",
  isLight: false,
  fontWeight: FontWeight.normal,
  widgetTheme: WidgetTheme(
    tooltipIconColor: Colors.white,
    iconButtonColor: ButtonColor(
      iconColor: Colors.white54,
      hoverIconColor: Colors.white,
      hoverBackgroundColor: const Color.fromRGBO(33, 33, 33, 1.0),
      backgroundColor: const Color.fromRGBO(33, 33, 33, 1.0),
    ),
    showHideButtonColor: ButtonColor(
      iconColor: Colors.white70,
      textColor: Colors.white70,
      backgroundColor: const Color.fromRGBO(33, 33, 33, 1.0),
      hoverIconColor: Colors.white70,
      hoverBackgroundColor: Colors.transparent,
    ),
    switchColor: SwitchColor(
      activeColor: Colors.green,
      focusColor: Colors.lightGreen,
    ),
    dropDownColor: DropDownColor(
      dropDownBackgroundColor: const Color.fromRGBO(25, 25, 25, 1),
      itemTextColor: Colors.white,
    ),
    textFieldColor: TextFieldColor(
      focusBorderColor: const Color.fromRGBO(53, 89, 143, 1),
      borderColor: const Color.fromRGBO(65, 65, 65, 1),
      fillColor: const Color.fromRGBO(56, 56, 56, 0.9),
      textColor: Colors.white,
      cursorColor: Colors.white,
    ),
  ),
  contextMenuTheme: ContextMenuTheme(
    backgroundColor: const Color.fromRGBO(35, 35, 35, 1.0),
    itemDisabledTextColor: Colors.grey,
    borderColor: Colors.transparent,
  ),
  downloadProgressDialogTheme: DownloadProgressDialogTheme(
    resumeColor: const ButtonColor(
      iconColor: Colors.transparent,
      backgroundColor: Color.fromRGBO(24, 150, 91, 1.0),
      hoverIconColor: Colors.transparent,
      hoverBackgroundColor: Color.fromRGBO(3, 114, 59, 1.0),
      hoverTextColor: Colors.white,
      textColor: Colors.white,
      borderColor: Color.fromRGBO(24, 150, 91, 1.0),
      borderHoverColor: Colors.green,
    ),
    pauseColor: const ButtonColor(
      iconColor: Colors.white70,
      hoverIconColor: Colors.transparent,
      textColor: Colors.white70,
      hoverBackgroundColor: Color.fromRGBO(244, 67, 54, 0.5),
      hoverTextColor: Colors.white,
      backgroundColor: Color.fromRGBO(244, 67, 54, 0.7),
      borderColor: Color.fromRGBO(63, 19, 19, 0.5),
      // borderHoverColor: Colors.red,
    ),
  ),
  topMenuTheme: const TopMenuTheme(
    backgroundColor: const Color.fromRGBO(20, 20, 20, 0.85),
    disabledHoverColor: Colors.white10,
    addUrlColor: const ButtonColor(
      iconColor: const Color.fromRGBO(56, 209, 82, 0.9),
      hoverIconColor: const Color.fromRGBO(56, 209, 82, 0.9),
      hoverBackgroundColor: const Color.fromRGBO(56, 209, 82, 0.2),
    ),
    downloadColor: const ButtonColor(
      iconColor: const Color.fromRGBO(56, 209, 82, 0.9),
      hoverIconColor: const Color.fromRGBO(56, 209, 82, 0.9),
      hoverBackgroundColor: const Color.fromRGBO(56, 209, 82, 0.2),
    ),
    stopColor: const ButtonColor(
      iconColor: const Color.fromRGBO(163, 23, 30, 1),
      hoverIconColor: const Color.fromRGBO(163, 23, 30, 1),
      hoverBackgroundColor: const Color.fromRGBO(163, 23, 30, 0.3),
    ),
    checkForUpdateColor: const ButtonColor(
      iconColor: const Color.fromRGBO(0, 128, 128, 1),
      hoverIconColor: const Color.fromRGBO(0, 128, 128, 1),
      hoverBackgroundColor: const Color.fromRGBO(0, 128, 128, 0.3),
    ),
    stopAllColor: const ButtonColor(
      iconColor: const Color.fromRGBO(163, 23, 30, 1),
      hoverIconColor: const Color.fromRGBO(163, 23, 30, 1),
      hoverBackgroundColor: const Color.fromRGBO(163, 23, 30, 0.3),
    ),
    removeColor: const ButtonColor(
      iconColor: const Color.fromRGBO(163, 23, 30, 1),
      hoverIconColor: const Color.fromRGBO(163, 23, 30, 1),
      hoverBackgroundColor: const Color.fromRGBO(163, 23, 30, 0.3),
    ),
    addToQueueColor: const ButtonColor(
      iconColor: const Color.fromRGBO(0, 128, 128, 1),
      hoverIconColor: const Color.fromRGBO(0, 128, 128, 1),
      hoverBackgroundColor: const Color.fromRGBO(0, 128, 128, 0.3),
    ),
    extensionColor: const ButtonColor(
      iconColor: const Color.fromRGBO(0, 128, 128, 1),
      hoverIconColor: const Color.fromRGBO(0, 128, 128, 1),
      hoverBackgroundColor: const Color.fromRGBO(0, 128, 128, 0.3),
    ),
    searchColor: const ButtonColor(
      iconColor: const Color.fromRGBO(0, 128, 128, 1),
      hoverIconColor: const Color.fromRGBO(0, 128, 128, 1),
      hoverBackgroundColor: const Color.fromRGBO(0, 128, 128, 0.3),
    ),
    createQueueColor: const ButtonColor(
      iconColor: const Color.fromRGBO(56, 209, 82, 0.9),
      hoverIconColor: const Color.fromRGBO(56, 209, 82, 0.9),
      hoverBackgroundColor: const Color.fromRGBO(56, 209, 82, 0.2),
    ),
    startQueueColor: const ButtonColor(
      iconColor: const Color.fromRGBO(56, 209, 82, 0.9),
      hoverIconColor: const Color.fromRGBO(56, 209, 82, 0.9),
      hoverBackgroundColor: const Color.fromRGBO(56, 209, 82, 0.2),
    ),
    stopQueueColor: const ButtonColor(
      iconColor: const Color.fromRGBO(163, 23, 30, 1),
      hoverIconColor: const Color.fromRGBO(163, 23, 30, 1),
      hoverBackgroundColor: const Color.fromRGBO(163, 23, 30, 0.3),
    ),
    scheduleQueueColor: const ButtonColor(
      iconColor: const Color.fromRGBO(56, 209, 82, 0.9),
      hoverIconColor: const Color.fromRGBO(56, 209, 82, 0.9),
      hoverBackgroundColor: const Color.fromRGBO(56, 209, 82, 0.2),
    ),
  ),
  sideMenuTheme: SideMenuTheme(
    settingIconColor: Colors.white,
    backgroundColor: const Color.fromRGBO(20, 20, 20, 1),
    briskLogoColor: Color.fromRGBO(53, 89, 143, 1),
    activeTabIconColor: Colors.white,
    activeTabBackgroundColor: const Color.fromRGBO(53, 89, 143, 1),
    tabHoverColor: const Color.fromRGBO(64, 65, 66, 0.3),
    tabIconColor: Colors.white,
    tabBackgroundColor: Colors.transparent,
    expansionTileExpandedColor: const Color.fromRGBO(64, 65, 66, 0.8),
    expansionTileItemActiveColor: const Color.fromRGBO(10, 126, 242, 0.8),
    expansionTileItemHoverColor: const Color.fromRGBO(64, 65, 66, 0.2),
  ),
  downloadGridTheme: DownloadGridTheme(
    rowTextColor: Colors.white,
    titleColumnTextColor: Colors.white,
    backgroundColor: const Color.fromRGBO(30, 30, 30, 1),
    activeRowColor: const Color.fromRGBO(49, 48, 48, 1),
    checkedRowColor: Color.fromRGBO(36, 63, 103, 1),
    borderColor: Colors.black26,
    rowColor: Colors.black26,
  ),
  settingTheme: SettingTheme(
    pageTheme: SettingPageTheme(
      groupBackgroundColor: const Color.fromRGBO(42, 43, 43, 1),
      groupTitleTextColor: Colors.white,
      titleTextColor: Colors.white,
    ),
    sideMenuTheme: SettingSideMenuTheme(
      backgroundColor: const Color.fromRGBO(26, 26, 26, 1.0),
      activeTabBackgroundColor: const Color.fromRGBO(53, 89, 143, 1),
      activeTabIconColor: Colors.white,
      inactiveTabIconColor: Colors.white,
      tabHoverBackgroundColor: const Color.fromRGBO(38, 38, 38, 1),
    ),
    saveButtonColor: ButtonColor(
      iconColor: Colors.transparent,
      hoverIconColor: Colors.transparent,
      hoverBackgroundColor: const Color.fromRGBO(3, 114, 59, 1.0),
      hoverTextColor: Colors.white,
      backgroundColor: const Color.fromRGBO(3, 114, 59, 1.0),
      textColor: Colors.white,
      borderColor: const Color.fromRGBO(24, 150, 91, 1.0),
      borderHoverColor: Colors.green,
    ),
    resetDefaultsButtonColor: ButtonColor(
      iconColor: Colors.transparent,
      hoverIconColor: Colors.transparent,
      hoverBackgroundColor: const Color.fromRGBO(20, 20, 20, 1),
      hoverTextColor: Colors.white,
      borderColor: Colors.transparent,
      textColor: Colors.white70,
      borderHoverColor: const Color.fromRGBO(53, 89, 143, 1),
    ),
  ),
  queuePageTheme: QueuePageTheme(
    backgroundColor: const Color.fromRGBO(30, 30, 30, 1),
    queueItemTitleTextColor: Colors.white,
    queueItemTitleDetailsTextColor: Colors.grey,
    queueItemHoverColor: Colors.white12,
  ),
  alertDialogTheme: AlertDialogTheme(
    backgroundColor: const Color.fromRGBO(20, 20, 20, 1),
    innerContainerBorderColor: Colors.white30,
    cancelColor: ButtonColor(
      iconColor: Colors.transparent,
      hoverIconColor: Colors.transparent,
      textColor: Colors.white,
      hoverBackgroundColor: const Color.fromRGBO(244, 67, 54, 1),
      hoverTextColor: Colors.white,
      backgroundColor: Color.fromRGBO(45, 45, 45, 0.5),
      borderColor: Colors.transparent,
      borderHoverColor: Colors.red,
    ),
    secondaryMiscButtonColor: ButtonColor(
      iconColor: Colors.transparent,
      hoverIconColor: Colors.transparent,
      hoverBackgroundColor: const Color.fromRGBO(45, 45, 45, 0.4),
      hoverTextColor: const Color.fromRGBO(53, 89, 143, 1),
      textColor: Colors.white,
      borderColor: Colors.transparent,
      backgroundColor: const Color.fromRGBO(45, 45, 45, 0.5),
    ),
    primaryMiscButtonColor: ButtonColor(
      iconColor: Colors.transparent,
      hoverIconColor: Colors.transparent,
      hoverBackgroundColor: const Color.fromRGBO(76, 117, 173, 1.0),
      hoverTextColor: Colors.white,
      textColor: Colors.white,
      backgroundColor: const Color.fromRGBO(53, 89, 143, 1),
    ),
    iconColor: Colors.white,
    checkBoxColor: CheckBoxColor(
      borderColor: Colors.grey,
      activeColor: const Color.fromRGBO(53, 89, 143, 1),
    ),
    acceptButtonColor: ButtonColor(
      iconColor: Colors.transparent,
      backgroundColor: const Color.fromRGBO(24, 150, 91, 1.0),
      hoverIconColor: Colors.transparent,
      hoverBackgroundColor: const Color.fromRGBO(3, 114, 59, 1.0),
      hoverTextColor: Colors.white,
      textColor: Colors.white,
      borderColor: const Color.fromRGBO(24, 150, 91, 1.0),
      borderHoverColor: Colors.green,
    ),
    declineButtonColor: ButtonColor(
      iconColor: Colors.transparent,
      hoverIconColor: Colors.transparent,
      textColor: Colors.white,
      hoverBackgroundColor: const Color.fromRGBO(244, 67, 54, 0.6),
      hoverTextColor: Colors.white,
      backgroundColor: const Color.fromRGBO(45, 45, 45, 0.5),
      borderColor: Colors.transparent,
      borderHoverColor: Colors.red,
    ),
    deleteConfirmColor: ButtonColor(
      iconColor: Colors.transparent,
      hoverIconColor: Colors.transparent,
      hoverTextColor: Colors.white,
      hoverBackgroundColor: const Color.fromRGBO(241, 3, 3, 1.0),
      backgroundColor: const Color.fromRGBO(220, 38, 38, 1),
      textColor: Colors.white,
    ),
    deleteCancelColor: ButtonColor(
      iconColor: Colors.transparent,
      hoverIconColor: Colors.transparent,
      hoverBackgroundColor: const Color.fromRGBO(61, 61, 61, 1.0),
      backgroundColor: const Color.fromRGBO(37, 37, 37, 1.0),
      textColor: Colors.white70,
    ),
    surfaceColor: const Color.fromRGBO(33, 33, 33, 1.0),
  ),
);
